"""Verify the password show/hide control on every page that has a password field.

Checks the things that would fail silently in production:
  * every password input is wrapped in exactly one `.pw-field`,
  * every wrapper has exactly one toggle button,
  * each button's `aria-controls` names the id of the input it sits beside,
  * the toggle is a `type="button"` (a bare button would submit the form),
  * the input's own attributes survived the macro (`required`, `autocomplete`,
    `minlength`, `autofocus` are what the auth and admin logic depend on),
  * the script that wires the button is actually loaded by the page.

Run: python _verify_password.py
"""
from __future__ import annotations

import hashlib
import re
import secrets
import sys
from dataclasses import replace
from datetime import timedelta

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.auth import RESET_TTL_MINUTES
from app.plans import spec_rows
from app.web import create_app
from config import get_settings
from database.models import ROLE_ADMIN, ROLE_CLIENT, Base
from database.repository import Repository
from trading import time_utils as tu

PASSWORD = "test-password-long-enough"
CSRF = "test-csrf"

#: page -> expected number of password inputs
PAGES: dict[str, int] = {}

failures: list[str] = []
checks = 0


def need(cond: bool, msg: str) -> None:
    global checks
    checks += 1
    if not cond:
        failures.append(msg)


#: An input tag, or the whole wrapper. Regex is enough here: the markup is
#: generated by one macro, so its shape is known.
INPUT = re.compile(r'<input\b[^>]*type="password"[^>]*>', re.S)
FIELD = re.compile(r'<div class="pw-field">(.*?)</div>', re.S)
TOGGLE = re.compile(r'<button\b[^>]*data-pw-toggle[^>]*>', re.S)


def audit(page: str, body: str, expected: int) -> None:
    inputs = INPUT.findall(body)
    need(len(inputs) == expected,
         f"{page}: {len(inputs)} password inputs, expected {expected}")

    fields = FIELD.findall(body)
    need(len(fields) == len(inputs),
         f"{page}: {len(fields)} .pw-field wrappers for {len(inputs)} inputs")

    for chunk in fields:
        inner_inputs = INPUT.findall(chunk)
        need(len(inner_inputs) == 1,
             f"{page}: wrapper holds {len(inner_inputs)} password inputs")
        buttons = TOGGLE.findall(chunk)
        need(len(buttons) == 1,
             f"{page}: wrapper has {len(buttons)} toggle buttons, expected 1")
        if len(buttons) != 1 or len(inner_inputs) != 1:
            continue
        button, inp = buttons[0], inner_inputs[0]

        need('type="button"' in button,
             f"{page}: toggle is not type=button (would submit the form)")

        m = re.search(r'id="([^"]+)"', inp)
        ctl = re.search(r'aria-controls="([^"]+)"', button)
        need(bool(m) and bool(ctl) and m.group(1) == ctl.group(1),
             f"{page}: aria-controls {ctl and ctl.group(1)!r} does not match "
             f"input id {m and m.group(1)!r}")

        need('aria-pressed="false"' in button,
             f"{page}: toggle has no initial aria-pressed")
        need('aria-label=' in button,
             f"{page}: toggle has no accessible name")
        # The two glyphs are the visual state; without both, one state is blank.
        need('pw-toggle-eye-off' in chunk and 'pw-toggle-eye"' in chunk,
             f"{page}: toggle is missing one of its two state icons")

    # Attributes the surrounding app logic relies on must survive the macro.
    for inp in inputs:
        for attr in ("required", "autocomplete"):
            need(attr in inp, f"{page}: input lost `{attr}`: {inp[:90]}")

    need("js/password.js" in body, f"{page}: password.js is not loaded")


def sign_in(client, repo, username, role, plan=None):
    user = repo.create_user(username=username, password_hash_or_plain=PASSWORD,
                            role=role, display_name=username,
                            subscribe=(role == ROLE_CLIENT))
    if plan:
        repo.sync_plans(spec_rows())
        p = repo.get_plan_by_key(plan)
        ref = f"pw-{plan}-{user.id}"
        repo.create_payment(user_id=user.id, plan=p, reference=ref,
                            amount_minor=p.price_minor, currency=p.currency)
        payment, _ = repo.settle_payment(ref, provider_tx_id=f"flw-{ref}",
                                         amount_minor=p.price_minor,
                                         currency=p.currency,
                                         payload={"status": "successful"})
        repo.activate_subscription(user_id=user.id, plan=p, payment=payment,
                                   period_days=30)
    client.get("/login")
    with client.session_transaction() as sess:
        sess["csrf"] = CSRF
    client.post("/login", data={"username": username, "password": PASSWORD,
                                "_csrf": CSRF})
    return user


def main() -> int:
    engine = create_engine("sqlite:///:memory:", future=True)
    Base.metadata.create_all(engine)
    repo = Repository(session=sessionmaker(bind=engine, expire_on_commit=False,
                                           future=True)())
    app = create_app(settings=replace(get_settings(), flask_secret_key="pwverify"),
                     repository=repo, setup_db=False)

    anon = app.test_client()
    for page, n in [("/login", 1), ("/register", 2)]:
        audit(page, anon.get(page).get_data(as_text=True), n)

    # /reset-password/<token> needs a live token.
    u = repo.create_user(username="pw-reset", password_hash_or_plain=PASSWORD,
                         role=ROLE_CLIENT, display_name="pw-reset")
    raw = secrets.token_urlsafe(32)
    repo.create_password_reset(
        user_id=u.id,
        token_hash=hashlib.sha256(raw.encode()).hexdigest(),
        expires_at=tu.now_utc() + timedelta(minutes=RESET_TTL_MINUTES))
    audit("reset-password",
          anon.get(f"/reset-password/{raw}").get_data(as_text=True), 2)

    client = app.test_client()
    sign_in(client, repo, "pw-client", ROLE_CLIENT, plan="vip")
    audit("/settings", client.get("/settings").get_data(as_text=True), 3)

    admin = app.test_client()
    sign_in(admin, repo, "pw-admin", ROLE_ADMIN)
    audit("/admin/clients", admin.get("/admin/clients").get_data(as_text=True), 1)

    target = repo.create_user(username="pw-target", password_hash_or_plain=PASSWORD,
                              role=ROLE_CLIENT, display_name="pw-target")
    audit(f"/admin/clients/{target.id}",
          admin.get(f"/admin/clients/{target.id}").get_data(as_text=True), 1)

    # The pages that must NOT have gained one.
    for page in ["/", "/dashboard", "/pricing", "/admin"]:
        body = (client if page in ("/dashboard",) else
                admin if page == "/admin" else anon).get(page).get_data(as_text=True)
        need("pw-toggle" not in body, f"{page}: unexpected password toggle")

    print(f"{checks} checks")
    if failures:
        print(f"\nFAIL ({len(failures)})")
        for f in failures:
            print(f"  - {f}")
        return 1
    print("\nPASS — every password field has one wired, correctly-labelled toggle")
    return 0


if __name__ == "__main__":
    sys.exit(main())
